USE [GD2C2020]

-- DECLARACION DE FOREIGN KEYS --

-- Tabla Compra

ALTER TABLE UNIX.Compra
ADD CONSTRAINT FK_CompraCliente 
FOREIGN KEY (CLIENTE_CODIGO) REFERENCES UNIX.Cliente(CLIENTE_CODIGO);

ALTER TABLE UNIX.Compra
ADD CONSTRAINT FK_CompraSucursal
FOREIGN KEY (SUCURSAL_CODIGO) REFERENCES UNIX.Sucursal(SUCURSAL_CODIGO);

-- Tabla CompraAutomovil
ALTER TABLE UNIX.CompraAutomovil
ADD CONSTRAINT FK_CompraAutomovilCompra
FOREIGN KEY (COMPRA_NRO) REFERENCES UNIX.Compra(COMPRA_NRO);

ALTER TABLE UNIX.CompraAutomovil
ADD CONSTRAINT FK_CompraAutomovilAutomovil
FOREIGN KEY (AUTOMOVIL_CODIGO) REFERENCES UNIX.Automovil(AUTOMOVIL_CODIGO);

--Tabla CompraPorAutoparte

ALTER TABLE UNIX.CompraPorAutoparte
ADD CONSTRAINT FK_CompraXAutopCompra
FOREIGN KEY (COMPRA_NRO) REFERENCES UNIX.Compra(COMPRA_NRO);

ALTER TABLE UNIX.CompraPorAutoparte
ADD CONSTRAINT FK_CompraXAutopAutop
FOREIGN KEY (AUTO_PARTE_CODIGO) REFERENCES UNIX.Autoparte(AUTO_PARTE_CODIGO);

-- Tabla Autoparte

ALTER TABLE UNIX.Autoparte
ADD CONSTRAINT FK_Autop_Modelo
FOREIGN KEY (MODELO_CODIGO) REFERENCES UNIX.Modelo(MODELO_CODIGO);

ALTER TABLE UNIX.Autoparte
ADD CONSTRAINT FK_Autop_Fabricante
FOREIGN KEY (FABRICANTE_CODIGO) REFERENCES UNIX.Fabricante(FABRICANTE_CODIGO);

--Tabla Automovil

ALTER TABLE UNIX.Automovil
ADD CONSTRAINT FK_Automovil_Modelo
FOREIGN KEY (MODELO_CODIGO) REFERENCES UNIX.Modelo(MODELO_CODIGO);

ALTER TABLE UNIX.Automovil
ADD CONSTRAINT FK_Automovil_Sucursal
FOREIGN KEY (SUCURSAL_CODIGO) REFERENCES UNIX.Sucursal(SUCURSAL_CODIGO);

--Tabla Modelo

ALTER TABLE UNIX.Modelo
ADD CONSTRAINT FK_Modelo_Fabricante
FOREIGN KEY (FABRICANTE_CODIGO) REFERENCES UNIX.Fabricante(FABRICANTE_CODIGO);

ALTER TABLE UNIX.Modelo
ADD CONSTRAINT FK_Modelo_TipoCaja
FOREIGN KEY (TIPO_CAJA_CODIGO) REFERENCES UNIX.TipoCaja(TIPO_CAJA_CODIGO);

ALTER TABLE UNIX.Modelo
ADD CONSTRAINT FK_Modelo_TipoMotor
FOREIGN KEY (TIPO_MOTOR_CODIGO) REFERENCES UNIX.TipoMotor(TIPO_MOTOR_CODIGO);

ALTER TABLE UNIX.Modelo
ADD CONSTRAINT FK_Modelo_TipoTransmision
FOREIGN KEY (TIPO_TRANSMISION_CODIGO) REFERENCES UNIX.TipoTransmision(TIPO_TRANSMISION_CODIGO);

ALTER TABLE UNIX.Modelo
ADD CONSTRAINT FK_Modelo_TipoAuto
FOREIGN KEY (TIPO_AUTO_CODIGO) REFERENCES UNIX.TipoAuto(TIPO_AUTO_CODIGO);

--Tabla ItemAutoparte

ALTER TABLE UNIX.ItemAutoparte
ADD CONSTRAINT FK_Item_Factura
FOREIGN KEY (FACTURA_NRO) REFERENCES UNIX.Factura(FACTURA_NRO);

ALTER TABLE UNIX.ItemAutoparte
ADD CONSTRAINT FK_Item_Autop
FOREIGN KEY (AUTO_PARTE_CODIGO) REFERENCES UNIX.Autoparte(AUTO_PARTE_CODIGO);



--Tabla ItemAutomovil

ALTER TABLE UNIX.ItemAutomovil
ADD CONSTRAINT FK_ItemAutomovil_Factura
FOREIGN KEY (FACTURA_NRO) REFERENCES UNIX.Factura(FACTURA_NRO);

ALTER TABLE UNIX.ItemAutomovil
ADD CONSTRAINT FK_ItemAutomovil_Automovil
FOREIGN KEY (AUTOMOVIL_CODIGO) REFERENCES UNIX.Automovil(AUTOMOVIL_CODIGO);

--Tabla Factura

ALTER TABLE UNIX.Factura
ADD CONSTRAINT FK_Factura_Cliente
FOREIGN KEY (CLIENTE_CODIGO) REFERENCES UNIX.Cliente(CLIENTE_CODIGO);

ALTER TABLE UNIX.Factura
ADD CONSTRAINT FK_Factura_Compra
FOREIGN KEY (COMPRA_NRO) REFERENCES UNIX.Compra(COMPRA_NRO);

ALTER TABLE UNIX.Factura
ADD CONSTRAINT FK_Factura_Sucursal
FOREIGN KEY (SUCURSAL_CODIGO) REFERENCES UNIX.Sucursal(SUCURSAL_CODIGO);
