USE [GD2C2020]
GO
BEGIN TRANSACTION

------------------------- CREACION DE TABLAS  -------------------------------
CREATE TABLE UNIX.BI_HechoModelo
(
    MODELO_CODIGO DECIMAL(18,0) NOT NULL,
    TIPO_CAJA_CODIGO decimal(18,0) NOT NULL,
    TIPO_MOTOR_CODIGO decimal(18,0),
    TIPO_TRANSMISION_CODIGO decimal(18,0) NOT NULL,
    TIPO_AUTO_CODIGO decimal(18,0) NOT NULL,
    FABRICANTE_CODIGO INT NOT NULL,
    POTENCIA_CODIGO INT NOT NULL,
    PROMEDIO_TIEMPO_STOCK INT,
    PRIMARY KEY(
      MODELO_CODIGO, TIPO_CAJA_CODIGO, TIPO_MOTOR_CODIGO, TIPO_TRANSMISION_CODIGO, TIPO_AUTO_CODIGO, FABRICANTE_CODIGO, POTENCIA_CODIGO
      )
);

CREATE TABLE UNIX.BI_Modelo
(
    MODELO_CODIGO DECIMAL(18,0) PRIMARY KEY,
    MODELO_NOMBRE nvarchar(255)
);

CREATE TABLE UNIX.BI_TipoCaja
(
    TIPO_CAJA_CODIGO decimal(18,0) PRIMARY KEY,
    TIPO_CAJA_DESC nvarchar(255)
);

CREATE TABLE UNIX.BI_TipoMotor
(
    TIPO_MOTOR_CODIGO decimal(18,0) PRIMARY KEY
);

CREATE TABLE UNIX.BI_Potencia(
  POTENCIA_CODIGO INT NOT NULL,
  POTENCIA NVARCHAR(255) NOT NULL,
  PRIMARY KEY(POTENCIA_CODIGO)
  )

CREATE TABLE UNIX.BI_Fabricante(
  FABRICANTE_CODIGO INT NOT NULL,
  FABRICANTE_NOMBRE NVARCHAR(255) NOT NULL,
  PRIMARY KEY(FABRICANTE_CODIGO)
  )

CREATE TABLE UNIX.BI_TipoAuto(
  TIPO_AUTO_CODIGO DECIMAL(18,0) NOT NULL,
  TIPO_AUTO_DESC NVARCHAR(255) NOT NULL,
  PRIMARY KEY(TIPO_AUTO_CODIGO)
  )

CREATE TABLE UNIX.BI_TipoTransmision(
  TIPO_TRANSMISION_CODIGO DECIMAL(18,0) NOT NULL,
  TIPO_TRANSMISION_DESC NVARCHAR(255) NOT NULL,
  PRIMARY KEY (TIPO_TRANSMISION_CODIGO)
)

CREATE TABLE UNIX.BI_Sucursal
(
    SUCURSAL_CODIGO INT PRIMARY KEY,
    SUCURSAL_DIRECCION nvarchar(255) NOT NULL,
    SUCURSAL_MAIL nvarchar(255) NOT NULL,
    SUCURSAL_TELEFONO decimal(18,0) NOT NULL,
    SUCURSAL_CIUDAD nvarchar(255) NOT NULL
);

CREATE TABLE UNIX.BI_Tiempo
(
    TIEMPO_CODIGO INT identity(1,1) PRIMARY KEY,
    MES INT NOT NULL,
    ANIO INT NOT NULL,
);

CREATE TABLE UNIX.BI_HechoSucursal
(
    TIEMPO_CODIGO INT NOT NULL,
    SUCURSAL_CODIGO INT,
    CANTIDAD_AUTOMOVILES_COMPRADOS INT NOT NULL,
	CANTIDAD_AUTOMOVILES_VENDIDOS INT NOT NULL,
	GANANCIAS_AUTOPARTES decimal(10,2) NOT NULL,
    GANANCIAS_AUTOMOVIL decimal(10,2) NOT NULL,
	PRECIO_PROMEDIO_AUTOMOVILES_VENDIDOS decimal(10,2) NOT NULL,
	PRECIO_PROMEDIO_AUTOMOVILES_COMPRADOS decimal(10,2) NOT NULL,
	CANTIDAD_AUTOPARTES_STOCK INT NOT NULL,
	PRIMARY KEY(TIEMPO_CODIGO,SUCURSAL_CODIGO)
);

  CREATE TABLE UNIX.BI_Edad(
  EDAD_CODIGO INT NOT NULL IDENTITY(1,1),
  EDAD NVARCHAR(255) NOT NULL
  PRIMARY KEY(EDAD_CODIGO)
  )


CREATE TABLE UNIX.BI_HechoEdades(
  EDAD_CODIGO INT NOT NULL,
  TIEMPO_CODIGO INT NOT NULL,
  CANTIDAD_AUTOMOVILES_COMPRADOS INT NOT NULL,
  CANTIDAD_AUTOMOVILES_VENDIDOS INT NOT NULL,
  GANANCIAS_AUTOMOVIL DECIMAL(10,2) NOT NULL,
  GANANCIAS_AUTOPARTES DECIMAL(10,2) NOT NULL,
  PRECIO_PROMEDIO_AUTOMOVILES_COMPRADOS DECIMAL(10,2) NOT NULL,
  PRECIO_PROMEDIO_AUTOMOVILES_VENDIDOS DECIMAL(10,2) NOT NULL,
  CANTIDAD_AUTOPARTES_STOCK INT NOT NULL
  )


--------------------------- ALTER TABLE (FOREING KEYS)  -----------------------------
ALTER TABLE UNIX.BI_HechoModelo
ADD CONSTRAINT FK_HechoModelo_Modelo
FOREIGN KEY (MODELO_CODIGO) REFERENCES UNIX.BI_Modelo(MODELO_CODIGO);

ALTER TABLE UNIX.BI_HechoModelo
ADD CONSTRAINT FK_HechoModelo_Fabricante
FOREIGN KEY (FABRICANTE_CODIGO) REFERENCES UNIX.BI_Fabricante(FABRICANTE_CODIGO);

ALTER TABLE UNIX.BI_HechoModelo
ADD CONSTRAINT FK_HechoModelo_TipoCaja
FOREIGN KEY (TIPO_CAJA_CODIGO) REFERENCES UNIX.BI_TipoCaja(TIPO_CAJA_CODIGO);

ALTER TABLE UNIX.BI_HechoModelo
ADD CONSTRAINT FK_HechoModelo_TipoMotor
FOREIGN KEY (TIPO_MOTOR_CODIGO) REFERENCES UNIX.BI_TipoMotor(TIPO_MOTOR_CODIGO);

ALTER TABLE UNIX.BI_HechoModelo
ADD CONSTRAINT FK_HechoModelo_TipoTransmision
FOREIGN KEY (TIPO_TRANSMISION_CODIGO) REFERENCES UNIX.BI_TipoTransmision(TIPO_TRANSMISION_CODIGO);

ALTER TABLE UNIX.BI_HechoModelo
ADD CONSTRAINT FK_HechoModelo_TipoAuto
FOREIGN KEY (TIPO_AUTO_CODIGO) REFERENCES UNIX.BI_TipoAuto(TIPO_AUTO_CODIGO);

ALTER TABLE UNIX.BI_HechoModelo
ADD CONSTRAINT FK_HechoModelo_Potencia
FOREIGN KEY (POTENCIA_CODIGO) REFERENCES UNIX.BI_Potencia(POTENCIA_CODIGO);

ALTER TABLE UNIX.BI_HechoSucursal
ADD CONSTRAINT FK_Tiempo_Sucursal
FOREIGN KEY (TIEMPO_CODIGO) REFERENCES UNIX.BI_Tiempo(TIEMPO_CODIGO);

ALTER TABLE UNIX.BI_HechoSucursal
ADD CONSTRAINT FK_Sucursal_Sucursal
FOREIGN KEY (SUCURSAL_CODIGO) REFERENCES UNIX.BI_Sucursal(SUCURSAL_CODIGO);

COMMIT



