BEGIN TRANSACTION

--------------------------- DIMENSIONES  -----------------------------

INSERT INTO UNIX.BI_Modelo(MODELO_CODIGO, MODELO_NOMBRE)
SELECT DISTINCT MODELO_CODIGO, MODELO_NOMBRE
FROM UNIX.Modelo
WHERE MODELO_CODIGO IS NOT NULL;


INSERT INTO UNIX.BI_TipoCaja (TIPO_CAJA_CODIGO, TIPO_CAJA_DESC)
SELECT DISTINCT TIPO_CAJA_CODIGO, TIPO_CAJA_DESC
FROM UNIX.TipoCaja
WHERE TIPO_CAJA_CODIGO IS NOT NULL;


INSERT INTO UNIX.BI_TipoMotor (TIPO_MOTOR_CODIGO)
SELECT DISTINCT TIPO_MOTOR_CODIGO
FROM UNIX.TipoMotor
WHERE TIPO_MOTOR_CODIGO IS NOT NULL;

INSERT INTO UNIX.BI_Fabricante (FABRICANTE_CODIGO, FABRICANTE_NOMBRE)
SELECT DISTINCT FABRICANTE_CODIGO, FABRICANTE_NOMBRE
FROM UNIX.Fabricante
WHERE FABRICANTE_CODIGO IS NOT NULL;

INSERT INTO UNIX.BI_TipoAuto (TIPO_AUTO_CODIGO, TIPO_AUTO_DESC)
SELECT DISTINCT TIPO_AUTO_CODIGO, TIPO_AUTO_DESC
FROM UNIX.TipoAuto
WHERE TIPO_AUTO_CODIGO IS NOT NULL;

INSERT INTO UNIX.BI_TipoTransmision (TIPO_TRANSMISION_CODIGO, TIPO_TRANSMISION_DESC)
SELECT DISTINCT TIPO_TRANSMISION_CODIGO, TIPO_TRANSMISION_DESC
FROM UNIX.TipoTransmision
WHERE TIPO_TRANSMISION_CODIGO IS NOT NULL;

INSERT INTO UNIX.BI_Potencia(POTENCIA_CODIGO, POTENCIA)
VALUES(1, '50-150cv'), (2, '151-300cv'), (3, '> 300cv');

INSERT INTO UNIX.BI_Sucursal(SUCURSAL_CODIGO, SUCURSAL_DIRECCION, SUCURSAL_MAIL, SUCURSAL_TELEFONO,SUCURSAL_CIUDAD)
SELECT SUCURSAL_CODIGO, SUCURSAL_DIRECCION, SUCURSAL_MAIL, SUCURSAL_TELEFONO,SUCURSAL_CIUDAD
FROM UNIX.Sucursal

INSERT INTO UNIX.BI_Tiempo(ANIO,MES)
	(SELECT DISTINCT YEAR(COMPRA_FECHA), MONTH(COMPRA_FECHA) FROM UNIX.Compra)
	UNION
	(SELECT DISTINCT YEAR(FACTURA_FECHA), MONTH(FACTURA_FECHA) FROM UNIX.Factura)

INSERT INTO UNIX.BI_Edad (EDAD_CODIGO, EDAD)
VALUES(1, '18 - 30 anios'), (2, '30 - 50 anios'), (3, '> 50 anios');


--------------------------- HECHO MODELO -----------------------------

IF(OBJECT_ID('tempdb.dbo.#TablaTemporal') IS NOT NULL)
	DROP TABLE #TablaTemporal
GO

CREATE TABLE #TablaTemporal (MODELO_CODIGO int, tiempoStockPromedio int)

INSERT INTO #TablaTemporal
SELECT MODELO_CODIGO, SUM(DATEDIFF (DAY, COMPRA_FECHA , FACTURA_FECHA ))/ COUNT(*) tiempoStockPromedio
FROM UNIX.Automovil a
JOIN UNIX.CompraAutomovil ca ON (ca.AUTOMOVIL_CODIGO = a.AUTOMOVIL_CODIGO)
JOIN UNIX.Compra c ON (c.COMPRA_NRO  = ca.COMPRA_NRO)
JOIN UNIX.ItemAutomovil ia ON (ia.AUTOMOVIL_CODIGO = a.AUTOMOVIL_CODIGO)
JOIN UNIX.Factura f ON (f.FACTURA_NRO = ia.FACTURA_NRO)
GROUP BY MODELO_CODIGO
ORDER BY MODELO_CODIGO


INSERT INTO UNIX.BI_HechoModelo 
(MODELO_CODIGO, TIPO_CAJA_CODIGO, TIPO_MOTOR_CODIGO, TIPO_TRANSMISION_CODIGO,
 TIPO_AUTO_CODIGO, FABRICANTE_CODIGO, POTENCIA_CODIGO, PROMEDIO_TIEMPO_STOCK)
SELECT m.MODELO_CODIGO, TIPO_CAJA_CODIGO, TIPO_MOTOR_CODIGO, TIPO_TRANSMISION_CODIGO, TIPO_AUTO_CODIGO, FABRICANTE_CODIGO,
  CASE
    WHEN MODELO_POTENCIA BETWEEN 49 AND 150  THEN 1
    WHEN MODELO_POTENCIA BETWEEN 151 AND 300  THEN 2
    ELSE  3
  END AS POTENCIA_CODIGO, tiempoStockPromedio
FROM UNIX.Modelo m
JOIN #TablaTemporal t ON (t.MODELO_CODIGO = m.MODELO_CODIGO);
GO

--------------------------- HECHO AUTOMOVIL COMPRA -----------------------------


CREATE OR ALTER FUNCTION CalcularRangoEdad(@FechaNacimiento DATETIME2)
RETURNS INT
BEGIN
  DECLARE @Anios INT
  DECLARE @Result INT
  SET @Anios = CAST(DATEDIFF (YEAR, @FechaNacimiento, GETDATE()) AS INT)
  
  IF (@Anios BETWEEN 18 AND 30) 
  BEGIN
    SET @Result = 1
  END

  IF (@Anios BETWEEN 31 AND 50) 
  BEGIN
    SET @Result = 2
  END

  IF (@Anios > 50) 
  BEGIN
    SET @Result = 3
  END

  RETURN @Result
END
GO

INSERT INTO UNIX.BI_HechoAutomovilCompra (TIEMPO_CODIGO, SUCURSAL_CODIGO, CLIENTE_EDAD_CODIGO, CANTIDAD_TOTAL_COMPRADA, COMPRA_TOTAL)
SELECT
  TIEMPO_CODIGO, s.SUCURSAL_CODIGO, dbo.CalcularRangoEdad(CLIENTE_FECHA_NAC) CLIENTE_EDAD_CODIGO, COUNT(*) CANTIDAD_TOTAL_COMPRADA, SUM(PRECIO_TOTAL) COMPRA_TOTAL
FROM UNIX.Compra c
JOIN UNIX.BI_Tiempo t ON (t.ANIO =  YEAR(COMPRA_FECHA) AND t.MES = MONTH(COMPRA_FECHA))
JOIN UNIX.BI_Sucursal s ON (s.SUCURSAL_CODIGO = c.SUCURSAL_CODIGO)
JOIN UNIX.Cliente cl ON (cl.CLIENTE_CODIGO = c.CLIENTE_CODIGO)
WHERE TIPO_COMPRA = 'AM'
GROUP BY TIEMPO_CODIGO, s.SUCURSAL_CODIGO, dbo.CalcularRangoEdad(CLIENTE_FECHA_NAC)
ORDER BY TIEMPO_CODIGO, SUCURSAL_CODIGO, CLIENTE_EDAD_CODIGO;


--------------------------- HECHO AUTOMOVIL VENTA -----------------------------

INSERT INTO UNIX.BI_HechoAutomovilVenta (TIEMPO_CODIGO, SUCURSAL_CODIGO, CLIENTE_EDAD_CODIGO, CANTIDAD_TOTAL_VENDIDA, VENTA_TOTAL)
SELECT
  TIEMPO_CODIGO, s.SUCURSAL_CODIGO, dbo.CalcularRangoEdad(CLIENTE_FECHA_NAC) CLIENTE_EDAD_CODIGO, COUNT(*) CANTIDAD_TOTAL_COMPRADA, SUM(PRECIO_TOTAL) COMPRA_TOTAL
FROM UNIX.Factura f
JOIN UNIX.BI_Tiempo t ON (t.ANIO =  YEAR(FACTURA_FECHA) AND t.MES = MONTH(FACTURA_FECHA))
JOIN UNIX.BI_Sucursal s ON (s.SUCURSAL_CODIGO = f.SUCURSAL_CODIGO)
JOIN UNIX.Cliente cl ON (cl.CLIENTE_CODIGO = f.CLIENTE_CODIGO)
WHERE TIPO_PRODUCTO = 'AM'
GROUP BY TIEMPO_CODIGO, s.SUCURSAL_CODIGO, dbo.CalcularRangoEdad(CLIENTE_FECHA_NAC)
ORDER BY TIEMPO_CODIGO, SUCURSAL_CODIGO, CLIENTE_EDAD_CODIGO;

COMMIT TRANSACTION


SELECT * FROM UNIX.BI_HechoAutomovilCompra


SELECT * FROM UNIX.BI_Edad

GO;
-- AUTOMOVILES x MES x SUCURSAL: CANTIDAD COMPRADA Y PRECIO TOTAL COMPRADO
SELECT SUCURSAL_CODIGO, MONTH(COMPRA_FECHA) mes, YEAR(COMPRA_FECHA) anio,
    COUNT(*) cantidad_comprada, SUM(c.PRECIO_TOTAL) precio_compra,AVG(PRECIO_TOTAL) promedio_compra
FROM UNIX.COMPRA c
WHERE TIPO_COMPRA = 'AM'
GROUP BY SUCURSAL_CODIGO, MONTH(COMPRA_FECHA),YEAR(COMPRA_FECHA)
HAVING YEAR(COMPRA_FECHA) = 2018 AND MONTH(COMPRA_FECHA) = 1

SELECT * FROM UNIX.BI_Tiempo WHERE TIEMPO_CODIGO = 3



  -- AUTOMOVILES x MES x SUCURSAL: CANTIDAD VENDIDA  Y PRECIO TOTAL VENDIDO
  SELECT SUCURSAL_CODIGO, MONTH(FACTURA_FECHA) mes, YEAR(FACTURA_FECHA) anio,
    COUNT(*) cantidad_vendida, SUM(PRECIO_TOTAL) precio_vendido, AVG(PRECIO_TOTAL) promedio_venta
  FROM UNIX.Factura f
  WHERE TIPO_PRODUCTO = 'AM' AND SUCURSAL_CODIGO = 1
  GROUP BY SUCURSAL_CODIGO, MONTH(FACTURA_FECHA),YEAR(FACTURA_FECHA)
  HAVING YEAR(FACTURA_FECHA) = 2018 AND MONTH(FACTURA_FECHA) = 3



------------------- Tabla intermedia datos automoviles  -------------------

SELECT 
  ac.SUCURSAL_CODIGO, ac.anio, ac.mes, cantidad_comprada, 
  promedio_compra, cantidad_vendida, promedio_venta, (precio_vendido - precio_compra) ganancias
INTO #automoviles
FROM 
  (
  -- AUTOMOVILES x MES x SUCURSAL: CANTIDAD COMPRADA Y PRECIO TOTAL COMPRADO
  SELECT SUCURSAL_CODIGO, MONTH(COMPRA_FECHA) mes, YEAR(COMPRA_FECHA) anio, 
      COUNT(*) cantidad_comprada, SUM(c.PRECIO_TOTAL) precio_compra,AVG(PRECIO_TOTAL) promedio_compra
  FROM UNIX.COMPRA c
  WHERE TIPO_COMPRA = 'AM'
  GROUP BY SUCURSAL_CODIGO, MONTH(COMPRA_FECHA),YEAR(COMPRA_FECHA)
  ) ac
JOIN 
  (
  -- AUTOMOVILES x MES x SUCURSAL: CANTIDAD VENDIDA  Y PRECIO TOTAL VENDIDO
  SELECT SUCURSAL_CODIGO, MONTH(FACTURA_FECHA) mes, YEAR(FACTURA_FECHA) anio,
    COUNT(*) cantidad_vendida, SUM(PRECIO_TOTAL) precio_vendido, AVG(PRECIO_TOTAL) promedio_venta
  FROM UNIX.Factura f
  WHERE TIPO_PRODUCTO = 'AM'
  GROUP BY SUCURSAL_CODIGO, MONTH(FACTURA_FECHA),YEAR(FACTURA_FECHA)
  ) av
ON (
    ac.SUCURSAL_CODIGO = av.SUCURSAL_CODIGO AND
    ac.anio = av.anio AND
    ac.mes = av.mes
  )


SELECT * FROM #automoviles
