BEGIN TRANSACTION
CREATE TABLE UNIX.BI_Sucursal
(
    SUCURSAL_CODIGO INT PRIMARY KEY,
    SUCURSAL_DIRECCION nvarchar(255) NOT NULL,
    SUCURSAL_MAIL nvarchar(255) NOT NULL,
    SUCURSAL_TELEFONO decimal(18,0) NOT NULL,
    SUCURSAL_CIUDAD nvarchar(255) NOT NULL
);

CREATE TABLE UNIX.BI_Tiempo
(
    TIEMPO_CODIGO INT identity(1,1) PRIMARY KEY,
    MES INT NOT NULL,
    ANIO INT NOT NULL,
);

CREATE TABLE UNIX.BI_HechoSucursal
(
    TIEMPO_CODIGO INT NOT NULL,
    SUCURSAL_CODIGO INT,
    CANTIDAD_AUTOMOVILES_COMPRADOS INT NOT NULL,
	CANTIDAD_AUTOMOVILES_VENDIDOS INT NOT NULL,
	GANANCIAS_AUTOPARTES decimal(10,2) NOT NULL,
    GANANCIAS_AUTOMOVIL decimal(10,2) NOT NULL,
	PRECIO_PROMEDIO_AUTOMOVILES_VENDIDOS decimal(10,2) NOT NULL,
	PRECIO_PROMEDIO_AUTOMOVILES_COMPRADOS decimal(10,2) NOT NULL,
	CANTIDAD_MAXIMA_AUTOPARTES_STOCK INT NOT NULL,
	PRIMARY KEY(TIEMPO_CODIGO,SUCURSAL_CODIGO)
);

  CREATE TABLE UNIX.BI_Edad(
  EDAD_CODIGO INT NOT NULL IDENTITY(1,1),
  EDAD NVARCHAR(255) NOT NULL
  PRIMARY KEY(EDAD_CODIGO)
  )


CREATE TABLE UNIX.BI_HechoEdades(
  EDAD_CODIGO INT NOT NULL,
  TIEMPO_CODIGO INT NOT NULL,
  CANTIDAD_AUTOMOVILES_COMPRADOS INT NOT NULL,
  CANTIDAD_AUTOMOVILES_VENDIDOS INT NOT NULL,
  GANANCIAS_AUTOMOVIL DECIMAL(10,2) NOT NULL,
  GANANCIAS_AUTOPARTES DECIMAL(10,2) NOT NULL,
  PRECIO_PROMEDIO_AUTOMOVILES_COMPRADOS DECIMAL(10,2) NOT NULL,
  PRECIO_PROMEDIO_AUTOMOVILES_VENDIDOS DECIMAL(10,2) NOT NULL,
  CANTIDAD_AUTOPARTES_STOCK INT NOT NULL
  )

ALTER TABLE UNIX.BI_HechoSucursal
ADD CONSTRAINT FK_Tiempo_Sucursal
FOREIGN KEY (TIEMPO_CODIGO) REFERENCES UNIX.BI_Tiempo(TIEMPO_CODIGO);

ALTER TABLE UNIX.BI_HechoSucursal
ADD CONSTRAINT FK_Sucursal_Sucursal
FOREIGN KEY (SUCURSAL_CODIGO) REFERENCES UNIX.BI_Sucursal(SUCURSAL_CODIGO);


INSERT INTO UNIX.BI_Sucursal(SUCURSAL_CODIGO, SUCURSAL_DIRECCION, SUCURSAL_MAIL, SUCURSAL_TELEFONO,SUCURSAL_CIUDAD)
SELECT SUCURSAL_CODIGO, SUCURSAL_DIRECCION, SUCURSAL_MAIL, SUCURSAL_TELEFONO,SUCURSAL_CIUDAD
FROM UNIX.Sucursal


INSERT INTO UNIX.BI_Tiempo(ANIO,MES)
	(SELECT DISTINCT YEAR(COMPRA_FECHA), MONTH(COMPRA_FECHA) FROM UNIX.Compra)
	UNION
	(SELECT DISTINCT YEAR(FACTURA_FECHA), MONTH(FACTURA_FECHA) FROM UNIX.Factura)




INSERT INTO UNIX.BI_Edad (EDAD)
VALUES('18 - 30 anios'),
    ('30 - 50 anios'),
    ('> 50 anios');
			
ROLLBACK TRANSACTION



SELECT * FROM UNIX.BI_HechoSucursal
SELECT * FROM UNIX.BI_Tiempo
SELECT * FROM UNIX.BI_Sucursal

SELECT TIEMPO

SELECT TOP 100 MODELO_POTENCIA FROM gd_esquema.Maestra WHERE MODELO_POTENCIA<150

