USE [GD2C2020]

-- CREACION DE ESQUEMA
CREATE SCHEMA UNIX;

-- CREACION DE TABLAS--

BEGIN TRANSACTION

CREATE TABLE UNIX.Cliente (
CLIENTE_CODIGO INT identity(1,1) PRIMARY KEY,
CLIENTE_APELLIDO nvarchar(255),
CLIENTE_NOMBRE nvarchar(255),
CLIENTE_DIRECCION nvarchar(255),
CLIENTE_DNI decimal(18,0),
CLIENTE_FECHA_NAC datetime2(3),
CLIENTE_MAIL nvarchar(255)
);


CREATE TABLE UNIX.Compra(
COMPRA_NRO decimal(18,0) PRIMARY KEY,
CLIENTE_CODIGO INT NOT NULL,
SUCURSAL_CODIGO INT NOT NULL,
COMPRA_FECHA datetime2(3),
TIPO_COMPRA char(2),
PRECIO_TOTAL decimal(18,2)
);


CREATE TABLE UNIX.CompraPorAutoparte(
COMPRA_NRO DECIMAL(18,0) ,
AUTO_PARTE_CODIGO DECIMAL(18,0),
COMPRA_CANT decimal(18,0),
COMPRA_PRECIO DECIMAL(18,0),
PRIMARY KEY (COMPRA_NRO, AUTO_PARTE_CODIGO)
);


CREATE TABLE UNIX.CompraAutomovil(
COMPRA_NRO DECIMAL(18,0) PRIMARY KEY,
AUTOMOVIL_CODIGO INT,
COMPRA_PRECIO DECIMAL(18,0)
);

CREATE TABLE UNIX.Autoparte(
AUTO_PARTE_CODIGO DECIMAL(18,0) PRIMARY KEY NOT NULL,
AUTO_PARTE_DESCRIPCION nvarchar(255),
SUCURSAL_CODIGO INT NOT NULL,
FABRICANTE_CODIGO INT NOT NULL,
MODELO_CODIGO DECIMAL(18,0) NOT NULL,
CATEGORIA_RUBRO varchar(255),
AUTO_PARTE_PRECIO decimal(18,2));


CREATE TABLE UNIX.Automovil(
AUTOMOVIL_CODIGO INT identity(1,1) PRIMARY KEY,
MODELO_CODIGO DECIMAL(18,0) NOT NULL,
AUTO_CANT_KMS decimal(18,0) NULL,
AUTO_NRO_CHASIS nvarchar(50) NULL,
AUTO_FECHA_ALTA datetime2(3) NULL,
AUTO_NRO_MOTOR nvarchar(50) NULL,
AUTO_PATENTE nvarchar(50) NULL,
SUCURSAL_CODIGO INT NOT NULL
);


CREATE TABLE UNIX.Fabricante(
FABRICANTE_CODIGO INT identity(1,1) PRIMARY KEY,
FABRICANTE_NOMBRE nvarchar(255)
);


CREATE TABLE UNIX.Sucursal(
SUCURSAL_CODIGO INT identity(1,1) PRIMARY KEY,
SUCURSAL_DIRECCION nvarchar(255),
SUCURSAL_MAIL nvarchar(255),
SUCURSAL_TELEFONO decimal(18,0),
SUCURSAL_CIUDAD nvarchar(255)
);


CREATE TABLE UNIX.Modelo(
MODELO_CODIGO DECIMAL(18,0) PRIMARY KEY,
MODELO_NOMBRE nvarchar(255),
MODELO_POTENCIA nvarchar(255),
ID_TIPO_AUTO INT,
ID_TIPO_MOTOR INT NOT NULL,
ID_TIPO_CAJA INT NOT NULL,
ID_TIPO_TRANSMISION INT NOT NULL,
FABRICANTE_CODIGO INT NOT NULL
);


CREATE TABLE UNIX.TipoAuto(
ID_TIPO_AUTO INT identity(1,1) PRIMARY KEY,
TIPO_AUTO_CODIGO decimal(18,0),
TIPO_AUTO_DESC nvarchar(255)
);


CREATE TABLE UNIX.TipoTransmision(
ID_TIPO_TRANSMISION INT identity(1,1) PRIMARY KEY,
TIPO_AUTO_CODIGO decimal(18,0) NULL,
TIPO_TRANSMISION_DESC nvarchar(255) NULL
);


CREATE TABLE UNIX.TipoCaja(
ID_TIPO_CAJA INT identity(1,1) PRIMARY KEY,
TIPO_CAJA_CODIGO decimal(18,0),
TIPO_CAJA_DESC nvarchar(255)
);


CREATE TABLE UNIX.TipoMotor(
ID_TIPO_MOTOR INT identity(1,1) PRIMARY KEY,
TIPO_MOTOR_CODIGO decimal(18,0)
);


CREATE TABLE UNIX.Factura(
FACTURA_NRO DECIMAL(18,0) PRIMARY KEY,
FACTURA_FECHA datetime2(3),
PRECIO_TOTAL DECIMAL(18,0),
SUCURSAL_CODIGO INT NOT NULL,
TIPO_PRODUCTO nvarchar(255),
CLIENTE_CODIGO INT NOT NULL,
COMPRA_NRO DECIMAL(18,0) NOT NULL
);


CREATE TABLE UNIX.ItemAutoparte(
FACTURA_NRO DECIMAL(18,0) ,
AUTO_PARTE_CODIGO DECIMAL(18,0),
CANT_FACTURADA decimal(18,0) NULL,
PRECIO_FACTURADO DECIMAL(18,0),
PRIMARY KEY (FACTURA_NRO, AUTO_PARTE_CODIGO)
);


CREATE TABLE UNIX.ItemAutomovil(
FACTURA_NRO DECIMAL(18,0),
AUTOMOVIL_CODIGO INT,
PRECIO_FACTURADO DECIMAL(18,0),
PRIMARY KEY(FACTURA_NRO, AUTOMOVIL_CODIGO)
);

COMMIT

-- DECLARACION DE FOREIGN KEYS --

-- Tabla Compra

ALTER TABLE UNIX.Compra
ADD CONSTRAINT FK_CompraCliente 
FOREIGN KEY (CLIENTE_CODIGO) REFERENCES UNIX.Cliente(CLIENTE_CODIGO);

ALTER TABLE UNIX.Compra
ADD CONSTRAINT FK_CompraSucursal
FOREIGN KEY (SUCURSAL_CODIGO) REFERENCES UNIX.Sucursal(SUCURSAL_CODIGO);

-- Tabla CompraAutomovil
ALTER TABLE UNIX.CompraAutomovil
ADD CONSTRAINT FK_CompraAutomovilCompra
FOREIGN KEY (COMPRA_NRO) REFERENCES UNIX.Compra(COMPRA_NRO);

ALTER TABLE UNIX.CompraAutomovil
ADD CONSTRAINT FK_CompraAutomovilAutomovil
FOREIGN KEY (AUTOMOVIL_CODIGO) REFERENCES UNIX.Automovil(AUTOMOVIL_CODIGO);

--Tabla CompraPorAutoparte

ALTER TABLE UNIX.CompraPorAutoparte
ADD CONSTRAINT FK_CompraXAutopCompra
FOREIGN KEY (COMPRA_NRO) REFERENCES UNIX.Compra(COMPRA_NRO);

ALTER TABLE UNIX.CompraPorAutoparte
ADD CONSTRAINT FK_CompraXAutopAutop
FOREIGN KEY (AUTO_PARTE_CODIGO) REFERENCES UNIX.Autoparte(AUTO_PARTE_CODIGO);

-- Tabla Autoparte

ALTER TABLE UNIX.Autoparte
ADD CONSTRAINT FK_Autop_Sucursal
FOREIGN KEY (SUCURSAL_CODIGO) REFERENCES UNIX.Sucursal(SUCURSAL_CODIGO);

ALTER TABLE UNIX.Autoparte
ADD CONSTRAINT FK_Autop_Modelo
FOREIGN KEY (MODELO_CODIGO) REFERENCES UNIX.Modelo(MODELO_CODIGO);

ALTER TABLE UNIX.Autoparte
ADD CONSTRAINT FK_Autop_Fabricante
FOREIGN KEY (FABRICANTE_CODIGO) REFERENCES UNIX.Fabricante(FABRICANTE_CODIGO);

--Tabla Automovil

ALTER TABLE UNIX.Automovil
ADD CONSTRAINT FK_Automovil_Modelo
FOREIGN KEY (MODELO_CODIGO) REFERENCES UNIX.Modelo(MODELO_CODIGO);

ALTER TABLE UNIX.Automovil
ADD CONSTRAINT FK_Automovil_Sucursal
FOREIGN KEY (SUCURSAL_CODIGO) REFERENCES UNIX.Sucursal(SUCURSAL_CODIGO);

--Tabla Modelo

ALTER TABLE UNIX.Modelo
ADD CONSTRAINT FK_Modelo_Fabricante
FOREIGN KEY (FABRICANTE_CODIGO) REFERENCES UNIX.Fabricante(FABRICANTE_CODIGO);

ALTER TABLE UNIX.Modelo
ADD CONSTRAINT FK_Modelo_TipoCaja
FOREIGN KEY (ID_TIPO_CAJA) REFERENCES UNIX.TipoCaja(ID_TIPO_CAJA);

ALTER TABLE UNIX.Modelo
ADD CONSTRAINT FK_Modelo_TipoMotor
FOREIGN KEY (ID_TIPO_MOTOR) REFERENCES UNIX.TipoMotor(ID_TIPO_MOTOR);

ALTER TABLE UNIX.Modelo
ADD CONSTRAINT FK_Modelo_TipoTransmision
FOREIGN KEY (ID_TIPO_TRANSMISION) REFERENCES UNIX.TipoTransmision(ID_TIPO_TRANSMISION);

ALTER TABLE UNIX.Modelo
ADD CONSTRAINT FK_Modelo_TipoAuto
FOREIGN KEY (ID_TIPO_AUTO) REFERENCES UNIX.TipoAuto(ID_TIPO_AUTO);

--Tabla ItemAutoparte

ALTER TABLE UNIX.ItemAutoparte
ADD CONSTRAINT FK_Item_Factura
FOREIGN KEY (FACTURA_NRO) REFERENCES UNIX.Factura(FACTURA_NRO);

ALTER TABLE UNIX.ItemAutoparte
ADD CONSTRAINT FK_Item_Autop
FOREIGN KEY (AUTO_PARTE_CODIGO) REFERENCES UNIX.Autoparte(AUTO_PARTE_CODIGO);



--Tabla ItemAutomovil

ALTER TABLE UNIX.ItemAutomovil
ADD CONSTRAINT FK_ItemAutomovil_Factura
FOREIGN KEY (FACTURA_NRO) REFERENCES UNIX.Factura(FACTURA_NRO);

ALTER TABLE UNIX.ItemAutomovil
ADD CONSTRAINT FK_ItemAutomovil_Automovil
FOREIGN KEY (AUTOMOVIL_CODIGO) REFERENCES UNIX.Automovil(AUTOMOVIL_CODIGO);

--Tabla Factura

ALTER TABLE UNIX.Factura
ADD CONSTRAINT FK_Factura_Cliente
FOREIGN KEY (CLIENTE_CODIGO) REFERENCES UNIX.Cliente(CLIENTE_CODIGO);

ALTER TABLE UNIX.Factura
ADD CONSTRAINT FK_Factura_Compra
FOREIGN KEY (COMPRA_NRO) REFERENCES UNIX.Compra(COMPRA_NRO);

ALTER TABLE UNIX.Factura
ADD CONSTRAINT FK_Factura_Sucursal
FOREIGN KEY (SUCURSAL_CODIGO) REFERENCES UNIX.Sucursal(SUCURSAL_CODIGO);


--------------------------------------------------------------------------
----------CREACION DE STORED PROCEDURES PARA MIGRACI�N-------------------


INSERT INTO UNIX.TipoMotor
SELECT DISTINCT TIPO_MOTOR_CODIGO
FROM gd_esquema.Maestra;

INSERT INTO UNIX.TipoCaja
SELECT DISTINCT TIPO_CAJA_CODIGO, TIPO_CAJA_DESC
FROM gd_esquema.Maestra;

INSERT INTO UNIX.TipoAuto
SELECT DISTINCT TIPO_AUTO_CODIGO, TIPO_AUTO_DESC
FROM gd_esquema.Maestra;

INSERT INTO UNIX.TipoTransmision
SELECT DISTINCT TIPO_TRANSMISION_CODIGO, TIPO_TRANSMISION_DESC
FROM gd_esquema.Maestra;



IF(OBJECT_ID('UNIX.Migrador_Fabricante') IS NOT NULL)
	DROP PROCEDURE UNIX.Migrador_Fabricante

GO
CREATE PROCEDURE UNIX.Migrador_Fabricante
AS
BEGIN
INSERT INTO UNIX.Fabricante
SELECT DISTINCT FABRICANTE_NOMBRE
FROM gd_esquema.Maestra;
END
GO

BEGIN

EXEC UNIX.Migrador_Fabricante

END
GO




-- LIMPIEZA

DROP TABLE UNIX.Automovil
DROP TABLE UNIX.Autoparte
DROP TABLE UNIX.Cliente
DROP TABLE UNIX.Compra
DROP TABLE UNIX.CompraPorAutoparte
DROP TABLE UNIX.CompraAutomovil
DROP TABLE UNIX.ItemAutomovil
DROP TABLE UNIX.ItemAutoparte
DROP TABLE UNIX.Fabricante
DROP TABLE UNIX.Factura
DROP TABLE UNIX.Item
DROP TABLE UNIX.Modelo
DROP TABLE UNIX.Sucursal
DROP TABLE UNIX.TipoAuto
DROP TABLE UNIX.TipoCaja
DROP TABLE UNIX.TipoMotor
DROP TABLE UNIX.TipoTransmision
DROP PROCEDURE UNIX.Migrador_Fabricante

DROP SCHEMA UNIX